name: Release

on:
  push:
    tags:
      - '*'
jobs:
  linux:
    name: Linux
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Update package list
        run: sudo apt-get update

      - name: Install stable toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true

      - name: Install OpenSSL
        run: sudo apt-get install openssl libssl-dev -y

      - name: Run cargo test
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --release

      - name: Build
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release

      - name: Compress
        run: tar -zcvf autoeq2camilladsp.tar.gz -C target/release autoeq2camilladsp

      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: autoeq2camilladsp.tar.gz
          asset_name: autoeq2camilladsp-linux-amd64.tar.gz
          tag: ${{ github.ref }}

  macos_arm:
    name: macOS aarch64
    runs-on: macos-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Install stable toolchain for arm
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
          target: aarch64-apple-darwin

      - name: Build
        uses: actions-rs/cargo@v1
        with:
          command: build
          args:  --release --target aarch64-apple-darwin
        env:
          SDKROOT: /Applications/Xcode_12.2.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX11.0.sdk
          MACOSX_DEPLOYMENT_TARGET: 11.0
          DEVELOPER_DIR: /Applications/Xcode_12.2.app

      - name: Compress
        run: 7z autoeq2camilladsp.zip target/aarch64-apple-darwin/release autoeq2camilladsp

      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v1-release
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: autoeq2camilladsp.zip
          asset_name: autoeq2camilladsp-macos-aarch64.zip
          tag: ${{ github.ref }}
